pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION = "eu-west-1"
    }
    stages {
        stage('Checkout SCM') {
            steps {
                git credentialsId: 'github-pat', branch: 'main', url: 'https://github.com/oezeakachi/AWSDevOpsProjects-obi.git'
            }
        }
        // Corrected: Moved 'Clean Terraform Cache' stage inside the 'stages' block
        stage('Clean Terraform Cache') {
            steps {
                script {
                    // Reverted path to original full path
                    dir('/var/lib/jenkins/workspace/Build/Project-7/tf-aws-eks/') {
                        sh 'rm -rf .terraform .terraform.lock.hcl terraform.tfstate terraform.tfstate.backup'
                    }
                }
            }
        }
        stage('Initializing Terraform') {
            steps {
                script {
                    // Reverted path to original full path
                    dir('/var/lib/jenkins/workspace/Build/Project-7/tf-aws-eks/') {
                        // Reverted terraform init command
                        sh 'terraform init'
                    }
                }
            }
        }
        stage('Validating Terraform') {
            steps {
                script {
                    // Reverted path to original full path
                    dir('/var/lib/jenkins/workspace/Build/Project-7/tf-aws-eks/') {
                        sh 'terraform validate'
                    }
                }
            }
        }
        stage('Terraform Plan') {
            steps {
                script {
                    // Reverted path to original full path
                    dir('/var/lib/jenkins/workspace/Build/Project-7/tf-aws-eks/') {
                        sh 'terraform plan -var-file=variables/prod.tfvars'
                    }
                    input(message: "Are you sure to proceed?", ok: "Proceed")
                }
            }
        }
        stage('Creating/Destroying EKS Cluster') {
            steps {
                script {
                    // Reverted path to original full path
                    dir('/var/lib/jenkins/workspace/Build/Project-7/tf-aws-eks/') {
                        // Original command with $action variable
                        sh 'terraform $action -var-file=variables/prod.tfvars -auto-approve'
                    }
                }
            }
        }
        stage('Deploying Nginx Application') {
            steps {
                script {
                    // Reverted path to original full path
                    dir('/var/lib/jenkins/workspace/Build/Project-7/manifest') {
                        sh 'aws eks update-kubeconfig --name my-eks-cluster'
                        // Reverted namespace creation command
                        sh 'kubectl create namespace eks-nginx-app'
                        sh 'kubectl apply -f deployment.yaml -n eks-nginx-app'
                        sh 'kubectl apply -f service.yaml -n eks-nginx-app'
                    }
                }
            }
        }
    }
    post {

        success {
            echo 'Pipeline finished successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}